"""Add proof of delivery image to Parcel

Revision ID: 994ff9adcfd5
Revises: c7a1fdaa0746
Create Date: 2025-09-25 19:38:36.416658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994ff9adcfd5'
down_revision = 'c7a1fdaa0746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_of_delivery_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('proof_of_delivery_image_url')

    # ### end Alembic commands ###
