"""Add new fields to parcel model

Revision ID: a1c670bec11e
Revises: 6c6064a3deb8
Create Date: 2025-09-25 17:35:16.389332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c670bec11e'
down_revision = '6c6064a3deb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recipient_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parcel_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('parcel_image_url')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('sender_phone')

    # ### end Alembic commands ###
