"""Add shipping_cost to Parcel model

Revision ID: c7a1fdaa0746
Revises: a1c670bec11e
Create Date: 2025-09-25 19:04:21.995287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a1fdaa0746'
down_revision = 'a1c670bec11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('shipping_cost')

    # ### end Alembic commands ###
